apiVersion: 1

datasources:
  - name: Sentinel Postgres
    type: postgres
    uid: sentinel-postgres
    access: proxy
    url: postgres:5432
    database: sentinel
    user: sentinel
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: sentinel_dev_password
